// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

let escaped = "abc";

let surrogatePair = "😀";

let concatenated = "ab";

let interpolated = `\x61${"b"}\u0063`;

function constantSwitch() {
  return 1;
}

const rawBridgeProgramValue = '\\n';
;

let rawBridgeExpression = '\\n';

let rawBridgeFunction = (() => '\\n');

let rawBridgeRegex = /\\n/;

Mocha.describe("String_literal_normalization_test", () => {
  Mocha.test("attribute payloads use semantic strings", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 31, characters 59-66", Math.max(1, 2), 2));
  Mocha.test("ordinary escapes have one semantic representation", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 33, characters 69-76", escaped, "abc"));
  Mocha.test("surrogate-pair escapes have one semantic representation", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 36, characters 7-14", surrogatePair, "😀"));
  Mocha.test("ordinary literals participate in constant folding", () => {
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 40, characters 7-14", concatenated, "ab");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 41, characters 7-14", 1, 1);
  });
  Mocha.test("template segments survive the ast0 bridge", () => Test_utils.eq("File \"string_literal_normalization_test.res\", line 44, characters 61-68", interpolated, "abc"));
  Mocha.test("raw extension payloads preserve source spelling through ast0", () => {
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 47, characters 7-14", rawBridgeExpression, "\\n");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 48, characters 7-14", rawBridgeFunction(), "\\n");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 49, characters 7-14", rawBridgeProgramValue, "\\n");
    Test_utils.eq("File \"string_literal_normalization_test.res\", line 50, characters 7-14", rawBridgeRegex.test("\\n"), true);
  });
});

export {
  escaped,
  surrogatePair,
  concatenated,
  interpolated,
  constantSwitch,
  rawBridgeExpression,
  rawBridgeFunction,
  rawBridgeRegex,
}
/*  Not a pure module */
